version: "3.7"
services:
# confluent images
#  zookeeper:
#    image: confluentinc/cp-zookeeper:6.1.0
#    ports:
#      - 2181:2181
#    environment:
#      - ZOOKEEPER_CLIENT_PORT=2181
#  kafka:
#    image: confluentinc/cp-kafka:6.1.0
#    depends_on:
#      - zookeeper
#    ports:
#      - 9092:9092
#    environment:
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: kafka-docker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: docker.for.mac.localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  application:
    build: .
    depends_on:
      - kafka
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
    ports:
      - 8080:8080
