version: "3.7"
services:
#  mq:
#    image: rabbitmq:3.8
#    volumes:
#      - ./rabbitmq:/var/lib/rabbitmq
#    ports:
#      - 5672:5672
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  kafka:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

#  elasticsearch:
#    image: elasticsearch:7.6.1
#    ports:
#      - 9200:9200
#      - 9300:9300
#    environment:
#      - discovery.type=single-node
#  kibana:
#    image: kibana:7.6.1
#    depends_on:
#      - elasticsearch
#    ports:
#      - 5601:5601
#  logstash:
#    image: logstash:7.6.1
#    depends_on:
#      - api-svc
#      - customer-svc
#      - inventory-svc
#      - order-svc
#      - payment-svc
#    environment:
#      - "CLOUDSTORE_ROOT=/logs"
#    volumes:
#      - "./logstash/:/usr/share/logstash/pipeline/:ro"
#      - api-svc-logs:/logs/api/log

#volumes:
#  api-svc-logs:
