spring:
  datasource:
    url: jdbc:h2:mem:bankaccount
    driverClassName: org.h2.Driver
    username: sa
    password: password
  cloud:
    stream:
      bindings:
        balanceIn:
          binder: kafka
          destination: balance
          group: input-group-1
        balanceOut:
          binder: kafka
          destination: balance
          group: output-group-1
        statementIn:
          binder: kafka
          destination: balance
          group: input-group-2
      default-binder: kafka
#      kafka:
#        binder:
#          brokers:
#          defaultBrokerPort:
logging:
  level:
    li:
      doerf: DEBUG
  #file: log/application.log
