name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: --no-daemon build
      - name: Archive bootjar
        uses: actions/upload-artifact@v2
        with:
          name: bootjar
          path: build/libs
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rlespinasse/github-slug-action@v2.x
      - name: Download bootjar
        uses: actions/download-artifact@v2
        with:
          name: bootjar
          path: build/libs
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u doerfli --password-stdin
      - run: docker build -f Dockerfile -t ghcr.io/doerfli/bankaccount:${{ env.GITHUB_REF_SLUG }} .
      - run: docker push ghcr.io/doerfli/bankaccount:${{ env.GITHUB_REF_SLUG }}
  dockerArm64:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rlespinasse/github-slug-action@v2.x
      - name: Download bootjar
        uses: actions/download-artifact@v2
        with:
          name: bootjar
          path: build/libs
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u doerfli --password-stdin
      - run: docker buildx build --platform linux/arm64 -f Arm64.Dockerfile -t ghcr.io/doerfli/bankaccount:${{ env.GITHUB_REF_SLUG }}_arm64 .
      - run: docker buildx push ghcr.io/doerfli/bankaccount:${{ env.GITHUB_REF_SLUG }}_arm64